name: Build, Lint, and Format Code

on: pull_request

permissions:
  contents: write

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node
        uses: actions/setup-node@v4.1.0

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Format
        run: npm run lint

      - name: Lint
        run: npm run lint

      - name: Commit changes if any
        uses: EndBug/add-and-commit@v9.1.4
